server:
  port: 8080
spring:
  data:
    redis:
      host: localhost
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: yangzhixuan
    driver-class-name: com.mysql.cj.jdbc.Driver
rocketmq:
  name-server: localhost:9876